CREATE TABLE CLASS (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
NAME TEXT NOT NULL,
CODE UNIQUE,
NUMBER_OF_STUDENTS INT,
MUMBER_OF_VIP INT,
AGE_AVERAGE INT,
MOST_POPULAR_CITY TEXT,
OLDEST_VIP INT,
YOUNGEST_VIP INT,
TOTAL_STUDENTS INT DEFAULT 0);

CREATE TABLE STUDENT (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
CLASS_ID INT,
NAME TEXT NOT NULL,
AGE INT,
ADDRESS_CITY TEXT,
VIP BIT default 'FALSE',
FOREIGN KEY(CLASS_ID) REFERENCES CLASS(ID));

INSERT INTO CLASS(ID,NAME)
VALUES 
   (1,'maths'),
   (2,'physics'),
   (3,'chemistry'),
   (4,'sport');
   
INSERT INTO STUDENT(CLASS_ID, NAME, AGE, ADDRESS_CITY, VIP)
VALUES 
   (1,'Alex', 25, 'Kiev','FALSE'),
   (2,'Haim',16, 'Ashdod','FALSE'),
   (3,'Klara', 17, 'Gomel', 'FALSE'),
   (4,'Petya', 18, 'Moskva', 'FALSE');
   
UPDATE CLASS SET NUMBER_OF_STUDENTS = (SELECT COUNT(*) 
FROM STUDENT WHERE STUDENT.CLASS_ID = CLASS.ID);

UPDATE CLASS SET NUMBER_OF_VIP = (SELECT COUNT(*) 
FROM STUDENT WHERE STUDENT.CLASS_ID = CLASS.ID AND STUDENT.VIP='TRUE');

UPDATE CLASS SET AGE_AVERAGE = (SELECT AVG (AGE) 
FROM STUDENT WHERE STUDENT.CLASS_ID = CLASS.ID);

UPDATE CLASS SET OLDEST_VIP = (SELECT max(AGE) 
FROM STUDENT WHERE STUDENT.CLASS_ID = CLASS.ID AND STUDENT.VIP='TRUE');

UPDATE CLASS SET YOUNGEST_VIP = (SELECT min(AGE) 
FROM STUDENT WHERE STUDENT.CLASS_ID = CLASS.ID AND STUDENT.VIP='TRUE');

